# Generated by Django 3.1 on 2020-08-08 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_evaluation',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='search',
            name='difficulty',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='search',
            name='duration',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='search',
            name='platform',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='searcher.difficulty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='searcher.duration'),
        ),
    ]
