# Generated by Django 3.1 on 2020-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='default_test', max_length=63),
            preserve_default=False,
        ),
    ]
