# Generated by Django 3.1 on 2020-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20200808_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='starter',
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AddField(
            model_name='search',
            name='language',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AlterField(
            model_name='course',
            name='evaluation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='difficulty',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='search',
            name='platform',
            field=models.CharField(max_length=31),
        ),
    ]
