# Generated by Django 3.1 on 2020-08-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20200808_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_time',
        ),
    ]
